# Development overrides for docker-compose.yml
# This file is automatically loaded by docker-compose and provides development-specific settings

services:
  www:
    environment:
      # Enable XDebug for PHPStorm
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
      XDEBUG_SESSION: PHPSTORM
      PHP_IDE_CONFIG: serverName=localhost
      
      # Development settings
      DRUPAL_CONFIG_SYNC_DIR: /opt/drupal/web/sites/default/files/config_sync
      
      # Show all errors in development
      PHP_ERROR_REPORTING: E_ALL
      PHP_DISPLAY_ERRORS: "On"
      PHP_DISPLAY_STARTUP_ERRORS: "On"
      
    # Mount local development files
    volumes:
      - './www:/opt/drupal'
      # Uncomment to use local farmOS development
      # - '../farmOS/web/profiles/farm:/opt/drupal/web/profiles/farm'
      
  db:
    # Expose PostgreSQL port for local database tools
    ports:
      - '5432:5432'